# docker-compose.yml
version: '3'
services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5050:80
    volumes:
      - ./:/var/www/html/
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: tianyi
      MYSQL_DATABASE: tianyi
      MYSQL_USER: ax-worker
      MYSQL_PASSWORD: tianyi
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
volumes:
    db_data:
